# Python script to convert dashboard assets into a C++ header file.
import os
import gzip

def file_to_hex_array(filepath):
    with open(filepath, 'rb') as f:
        data = f.read()
    
    # Compress data with gzip to save Pico flash memory
    compressed_data = gzip.compress(data)
    
    hex_str = ", ".join(f"0x{b:02X}" for b in compressed_data)
    return hex_str, len(compressed_data), len(data)

def main():
    base_dir = "/home/umut/citroen-can-interface/dashboard"
    html_path = os.path.join(base_dir, "dashboard.html")
    css_path = os.path.join(base_dir, "dashboard.css")
    js_path = os.path.join(base_dir, "dashboard.js")
    
    html_hex, html_comp_len, html_len = file_to_hex_array(html_path)
    css_hex, css_comp_len, css_len = file_to_hex_array(css_path)
    js_hex, js_comp_len, js_len = file_to_hex_array(js_path)
    
    header_content = f"""// Generated by scripts/generate_assets.py. Do not edit.
#pragma once
#include <cstdint>
#include <cstddef>

namespace psa {{
namespace assets {{

// Gzipped dashboard.html
inline constexpr uint8_t kHtmlData[] = {{ {html_hex} }};
inline constexpr size_t kHtmlCompLen = {html_comp_len};
inline constexpr size_t kHtmlLen = {html_len};

// Gzipped dashboard.css
inline constexpr uint8_t kCssData[] = {{ {css_hex} }};
inline constexpr size_t kCssCompLen = {css_comp_len};
inline constexpr size_t kCssLen = {css_len};

// Gzipped dashboard.js
inline constexpr uint8_t kJsData[] = {{ {js_hex} }};
inline constexpr size_t kJsCompLen = {js_comp_len};
inline constexpr size_t kJsLen = {js_len};

}} // namespace assets
}} // namespace psa
"""
    
    out_path = "/home/umut/citroen-can-interface/include/psa/dashboard_assets.h"
    with open(out_path, 'w') as f:
        f.write(header_content)
    print(f"Generated {out_path} successfully.")

if __name__ == "__main__":
    main()
